# Generated by Django 5.0.1 on 2024-02-02 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("message", "0004_alter_message_client_id_alter_message_mailing_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="send_status",
            field=models.CharField(
                choices=[("sent", "Отправлено"), ("not_sent", "Не отправлено")],
                max_length=32,
            ),
        ),
    ]
