# Generated by Django 5.0.1 on 2024-01-26 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={"verbose_name": "Рассылка", "verbose_name_plural": "Рассылки"},
        ),
    ]
